### ISSUE TITLE
[follow up] update of `message Location`

### ISSUE THREAD

**Issue by florianl** [open-telemetry/opentelemetry-ebpf-profiler#147]
With https://github.com/open-telemetry/semantic-conventions/pull/1188 a semantic convention will be introduced for profiles. These new attributes should be used as replacement for `message Location.type_index`, which will be removed with https://github.com/open-telemetry/opentelemetry-proto/pull/578.

Once a new version of OTel semantic convention is released, that includes https://github.com/open-telemetry/semantic-conventions/pull/1188, package `reporter` should be updated and 
1. Remove `Location.TypeIndex` - see https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/c96e12686646b106e9cc88a42d7551018062250c/reporter/otlp_reporter.go#L556-L557
2. Use these new attributes in `message Location`

**Comment by Rajamanosankari** [comment]
I would like to work on this.

**Comment by florianl** [comment]
`Location.TypeIndex` will be removed with https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/167/ and replaced with semantic convention attributes.

**Comment by florianl** [comment]
Closing as resolved with https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/167
