### ISSUE TITLE
Expose metric information

### ISSUE THREAD

**Issue by umanwizard** [open-telemetry/opentelemetry-ebpf-profiler#149]
Currently, we have metrics defined as JSON blobs, like so:

```
{
    "description": "I/O Duration: values are 'weighted # of milliseconds doing I/O'",
    "type": "gauge",
    "name": "IODuration",
    "field": "host.io.duration",
    "unit": "ms",
    "id": 3
  }
  ```
  
  however, an external user of the library cannot access this information without manually copying the `metrics.json` file into their own repo. It would be nice to expose all of this in Go so that the `ReportMetrics` interface can be implemented sensibly without duplication.

**Comment by athre0z** [comment]
Agreed -- we should just `go:embed` the file into the library and expose the parsed array in the API.
