### ISSUE TITLE
Add support for JDK23

### ISSUE THREAD

**Issue by athre0z** [open-telemetry/opentelemetry-ebpf-profiler#150]
JDK23 is currently in release-candidate status and expected to reach GA on 17th Sep. Attempting to profile it currently results in the following error:

```
ERRO[1084] Failed to handle new anonymous mapping for PID 2338658: JVM symbol 'CompiledMethod.Sizeof' not found
```

**Comment by athre0z** [comment]
Probably related: https://github.com/openjdk/jdk/commit/83eba863fec5ee7e30c4f9b11122ad1deed3d2ec

**Comment by athre0z** [comment]
I didn't complete this before my last day at Elastic, but my patches for the progress so far live here: https://github.com/athre0z/opentelemetry-ebpf-profiler/commit/e25c90dbe4b58bec31c6ba062c167a68d7c21163

It seemed to be generally working, though it still needs more testing and probably also some debugging. I had noticed a small percentage of unsymbolized frames.

**Comment by fabled** [comment]
Working on this now, wip tree at https://github.com/fabled/opentelemetry-ebpf-profiler/tree/tt-jdk23

I believe the metadata and immutable data fixup should resolve majority of issue. But will still follow up with further additional comments and documentation.
