### ISSUE TITLE
What Python versions are supported?

### ISSUE THREAD

**Issue by chengshuyi** [open-telemetry/opentelemetry-ebpf-profiler#210]
I see that the source code only supports Python 3.6-3.12, so are these the only versions supported currently? The following is a source code snippet：
```go
        minVer := pythonVer(3, 6)
	maxVer := pythonVer(3, 12)
	if version < minVer || version > maxVer {
		return nil, fmt.Errorf("unsupported Python %d.%d (need >= %d.%d and <= %d.%d)",
			major, minor,
			(minVer>>8)&0xff, minVer&0xff,
			(maxVer>>8)&0xff, maxVer&0xff)
	}
```

Thanks!

**Comment by rockdaboot** [comment]
Yes, this is correct.

**Comment by florianl** [comment]
With https://github.com/open-telemetry/opentelemetry-ebpf-profiler/pull/190 support for Python 3.13 was added.
