### ISSUE TITLE
failed to load system config: unexpected x86_fsbase_write_task (mov not found)

### ISSUE THREAD

**Issue by liangGTY** [open-telemetry/opentelemetry-ebpf-profiler#224]
When I run ebpf-profile in the docker container, it prompts
![CleanShot 2024-11-05 at 14 51 42@2x](https://github.com/user-attachments/assets/de47f6a1-ae68-47c3-81b5-63194d2c8b8d)

This is the command I run docker
`sudo docker run --name eBPF -it -u root --privileged --network host -v /etc/machine-id:/etc/machine-id:ro \-v /var/run/docker.sock:/var/run/docker.sock -v /sys/kernel/debug:/sys/kernel/debug:ro ubuntu:22.04 /bin/bash`

This uname -a output
`Linux hostname 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by florianl** [comment]
Hi @liangGTY 

Can you share some more information about the environment? Can you maybe share also the `config` file of the Linux kernel you are using?
My first impression is, that some Linux kernel CONF settings are preventing the read of memory and return only `0` values instead.

**Comment by liangGTY** [comment]
i run the docker container in a virtualized environment， in my docker container, no this config file.
this is my virtual machines config file [/boot/config-5.4.0-77-generic](https://gist.github.com/liangGTY/8560fe4fafff7f4e4dd73edff98167a6)

**Comment by florianl** [comment]
Thanks for the update. So if I follow correctly, then running ebpf-profiler directly on the machine works fine, while running it in the docker container on the same machine results the above shown error. It looks like the docker environment/configurations/settings or some security mechanisms around using docker are preventing to read memory.
Maybe someone with more experience around docker, can help here. The only docker run option, that I could think of, that might help is `--pid=host`.

**Comment by florianl** [comment]
ebpf-profiler attach to and uses Linux kernel information to do its job. As docker and the host machine share the same Linux kernel, all this information is used by ebpf-profiler.
