### ISSUE TITLE
Duplicate entries in  `Profile.attribute_table`

### ISSUE THREAD

**Issue by florianl** [open-telemetry/opentelemetry-ebpf-profiler#99]
With `getSampleAttributes()` attributes of a sample are always appended to  `Profile.attribute_table`:

https://github.com/elastic/otel-profiling-agent/blob/a0b8ba402a37161732f3e63334699aeaa21f96d8/reporter/otlp_reporter.go#L740C4-L761

As a result, in `Profile.attribute_table` there are multiple duplicate entries. In addition, as `Profile.attribute_table` does not hold a reference of the strings into `Profile.string_table` but stores each string with each attribute, the required bandwidth to transmit information increases significantly.

**Expected behavior**
Every attribute in `Profile.attribute_table` should be unique. This could result in more computational work upfront, as one has to check for existing elements before adding to `Profile.attribute_table`.

**Comment by christos68k** [comment]
@florianl Is this a theoretical concern or does the issue manifest currently? Looking at the keys we insert, in that function, they're all different. So if there's a clash, it must come from same keys being inserted by the logic in `getResource` method.
